from setuptools import find_packages, setup

setup(
    name='src',
    packages=find_packages(),
    version='0.1.0',
    description='ThThis is a group assignment for implementing BERT. The course is generated by LMU. The project tutor is Emilio Dorigatti.',
    author='Zhiwei, Simei',
    license='',
)
